apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spout
  namespace: tbd
  labels:
    team: tbd
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "4m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{image}}
  port: 8080
  ingresses:
    {{#each ingresses }}
    - "{{this}}"
    {{/each}}
  liveness:
    path: /isalive
    initialDelay: 5
  readiness:
    path: /isready
    initialDelay: 5
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      tenant: nav.no
      enabled: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "c0227409-2085-4eb2-b487-c4ba270986a3" # nais-tbd
          - id: "5206a646-a99e-4cd5-90e4-758cf7948cc8" # flex
      allowAllUsers: false
  prometheus:
    enabled: false
    path: /metrics
  kafka:
    pool: {{kafkaPool}}
  secureLogs:
    enabled: true
  env:
    - name: SUBTEAM
      value: spleiselaget
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
