apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spout
  namespace: tbd
  labels:
    team: tbd
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "4m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 5
  readiness:
    path: /isready
    initialDelay: 5
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  accessPolicy:
    inbound:
      rules:
        - application: speil
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  azure:
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /melding
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
      allowAllUsers: false
  prometheus:
    enabled: false
    path: /metrics
  env:
    - name: SUBTEAM
      value: spleiselaget
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
