name: Spout

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CODEOWNERS'
    branches:
      - main

jobs:
  set_version:
    name: set image name
    runs-on: ubuntu-latest
    steps:
      - name: create docker tag
        run: echo "TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
    outputs:
      image: spout:${{ env.TAG }}

  build:
    permissions:
      contents: "read"
      id-token: "write"
    name: build docker image
    runs-on: ubuntu-latest
    needs: set_version
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.x'
          cache: 'gradle'
      - name: test and build
        run: ./gradlew clean test build
      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
          tag: ${{ needs.set_version.outputs.image }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deployDev:
    name: deploy to dev
    needs: [set_version, build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/application.yml
          VARS: .nais/dev.json
          IMAGE: ${{ needs.build.outputs.image }}
          PRINT_PAYLOAD: true

  deployProd:
    name: deploy to prod
    needs: [set_version, build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/application.yml
          VARS: .nais/prod.json
          IMAGE: ${{ needs.build.outputs.image }}
          PRINT_PAYLOAD: true
